name: pull_printing_app
description: A Flutter frontend for pull printing with Azure AD authentication and job release.
publish_to: 'none' # Since this is internal to your company

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking & state management
  http: ^1.2.0
  dio: ^5.1.1
  provider: ^6.1.2

  # Azure AD authentication
  msal_flutter: ^2.0.1

  # Data & storage
  json_annotation: ^4.9.0
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2

  # UI & localization
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
